import pandas as pd
import glob
import os

data_directory = './data/'
output_filename = 'filtered_college_data.csv'

college_list = [
    'Bethel University', 'Bloomfield College', 'Mississippi Valley State University',
    'Fort Valley State University', 'University of Arkansas at Pine Bluff', 'Livingstone College',
    'Kentucky State University', 'Escuela de Artes Plasticas y Diseno de Puerto Rico',
    'Villa Maria College', 'Gallaudet University', 'Benedict College', 'Virginia Union University',
    'Bethune-Cookman University', 'St Luke\'s College', 'Bowie State University',
    'Wilberforce University', 'Virginia State University', 'University of the Virgin Islands',
    'Fayetteville State University', 'Alabama A & M University', 'Winston-Salem State University',
    'Texas Southern University', 'University of Puerto Rico-Carolina', 'Huston-Tillotson University',
    'Lamar University', 'Grambling State University', 'Delaware State University',
    'Southern University and A & M College', 'Coppin State University', 'Lewis-Clark State College',
    'Holy Family University', 'Governors State University', 'Norfolk State University',
    'Mount Carmel College of Nursing', 'Boise Bible College', 'Southern University at New Orleans',
    'Grand River Technical School', 'Carlow University', 'Gordon State College', 'Lincoln University',
    'Compass College of Film and Media', 'Texas A&M University-San Antonio',
    'Prairie View A & M University', 'Kentucky Christian University', 'Mercy College of Ohio',
    'Eastern New Mexico University-Main Campus', 'Alabama State University',
    'Dallas Christian College', 'Trinity College of Florida', 'West Virginia State University',
    'Warner University', 'Reading Hospital School of Health Sciences', 'William Penn University',
    'Morgan State University', 'Columbia College', 'Sul Ross State University',
    'Fairmont State University', 'Roosevelt University', 'Northwestern Oklahoma State University',
    'University of Puerto Rico-Aguadilla', 'Clark Atlanta University', 'North Carolina Central University',
    'Wilmington College', 'Clayton  State University', 'Rockford University', 'Alice Lloyd College',
    'Union College', 'University of Baltimore', 'Bluffton University', 'Cardinal Stritch University',
    'The University of Texas at El Paso', 'Life University', 'Davis & Elkins College',
    'Abraham Baldwin Agricultural College', 'Trinity Baptist College', 'Point University',
    'Rhode Island College', 'Alderson Broadd University', 'Francis Marion University',
    'West Liberty University', 'College of Coastal Georgia', 'Randall University', 'Presentation College',
    'Texas A&M University-Texarkana', 'Bluefield State University', 'Missouri Valley College',
    'Eastern Illinois University', 'Jersey College', 'Newberry College', 'Greenville University',
    'Iowa Wesleyan University', 'Rust College', 'Elizabeth City State University',
    'Texas A & M International University', 'Concord University', 'Oakland City University',
    'University of Providence', 'Thomas University', 'Bethany College', 'Ferrum College',
    'Central Baptist College', 'The University of Texas Permian Basin', 'Dominican University',
    'Spalding University', 'University of West Alabama', 'Southwestern Assemblies of God University',
    'Kean University', 'Dickinson State University', 'The Christ College of Nursing and Health Sciences',
    'Henderson State University', 'Louisiana State University-Alexandria', 'Alcorn State University',
    'University of Arkansas Community College-Morrilton', 'Columbus State University',
    'University of Hawaii at Hilo', 'Dunwoody College of Technology', 'Cleveland State University',
    'Defiance College', 'University of the Incarnate Word', 'The University of Texas Rio Grande Valley',
    'Southwestern Adventist University', 'Middle Georgia State University', 'Faulkner University',
    'Saint Mary-of-the-Woods College', 'York University', 'Bethel University', 'Jackson State University',
    'Valley City State University', 'University of Puerto Rico at Cayey', 'Oklahoma Wesleyan University',
    'Muskingum University', 'Metropolitan State University of Denver', 'Minot State University',
    'Texas Wesleyan University', 'University of West Georgia', 'McPherson College',
    'Southwestern College', 'Averett University', 'Valdosta State University', 'Keystone College',
    'Mount Aloysius College', 'Colorado State University Pueblo', 'New Mexico State University-Main Campus',
    'Judson University', 'Ferris State University', 'Ottawa University-Surprise', 'University of Hawaii-West Oahu',
    'Howard Payne University', 'Ottawa University-Ottawa', 'Tabor College', 'Eastern Nazarene College',
    'Felician University', 'Angelo State University', 'University of Houston-Downtown', 'Urshan College',
    'New England Institute of Technology', 'SUNY College of Agriculture and Technology at Cobleskill',
    'Texas Woman\'s University', 'Hannibal-LaGrange University', 'Keuka College', 'Tusculum University',
    'Central Methodist University-College of Graduate and Extended Studies', 'Baptist University of Florida',
    'University of Saint Mary', 'Central Methodist University-College of Liberal Arts and Sciences',
    'Northeastern State University', 'Cabarrus College of Health Sciences', 'University of North Texas at Dallas',
    'MidAmerica Nazarene University', 'Siena Heights University', 'University of the Cumberlands',
    'Westminster College', 'Troy University', 'Mississippi University for Women',
    'Trinity Bible College and Graduate School', 'Aultman College of Nursing and Health Sciences',
    'Williams Baptist University', 'University of Saint Francis-Fort Wayne', 'Baker University',
    'Adrian College', 'Southwest Minnesota State University', 'College of Saint Mary',
    'Medaille University', 'North Carolina A & T State University', 'Pfeiffer University',
    'Kettering College', 'East Central University', 'Southwestern Oklahoma State University',
    'Western Oregon University', 'Dakota Wesleyan University', 'Mount Marty University',
    'Texas A & M University-Commerce', 'West Texas A & M University', 'Marian University',
    'Mount Mary University', 'University of Wisconsin-Oshkosh', 'University of Wisconsin-Superior',
    'Auburn University at Montgomery', 'Fort Hays State University', 'Eastern Kentucky University',
    'Chowan University', 'Kentucky Wesleyan College', 'Erskine College', 'Hampton University',
    'Rocky Mountain College', 'Oklahoma Baptist University', 'Delta State University',
    'Jacksonville State University', 'Clarke University', 'Northwood University',
    'Southeast Missouri State University', 'Purdue University Northwest', 'Eastern Michigan University',
    'Sam Houston State University', 'Georgia Southern University', 'Radford University',
    'Pennsylvania Western University', 'Calvary University', 'Wright State University-Lake Campus',
    'Shorter University', 'Belhaven University', 'Wright State University-Main Campus',
    'Slippery Rock University of Pennsylvania', 'Saint Joseph\'s College of Maine', 'Nichols College',
    'Wilson College', 'Lincoln Memorial University', 'Concordia University Texas',
    'Central Connecticut State University', 'Indiana University of Pennsylvania-Main Campus',
    'Tarleton State University', 'Colorado Mesa University', 'Indiana University-South Bend',
    'Shepherd University', 'Upper Iowa University', 'SUNY Buffalo State University', 'Adams State University',
    'John Paul the Great Catholic University', 'Johnson University', 'Stephen F Austin State University',
    'LIM College', 'West Virginia Wesleyan College', 'Commonwealth University of Pennsylvania',
    'Johnson University Florida', 'Southern Illinois University-Carbondale', 'Indiana University-Northwest',
    'Belmont Abbey College', 'Lubbock Christian University', 'University of Virginia\'s College at Wise',
    'East Stroudsburg University of Pennsylvania', 'University of Michigan-Flint',
    'Charleston Southern University', 'Saginaw Valley State University', 'Johnson & Wales University-Online',
    'Johnson & Wales University-Providence', 'Columbia International University',
    'Johnson & Wales University-Charlotte', 'Georgia Southwestern State University',
    'Pacific Union College', 'Marietta College', 'Alvernia University', 'Cedar Crest College',
    'Illinois College', 'Trinity International University-Illinois', 'Sterling College', 'Lander University',
    'Florida Agricultural and Mechanical University', 'Truett McConnell University', 'Brevard College',
    'Southeastern Oklahoma State University', 'Spring Arbor University', 'University of South Carolina-Upstate',
    'Eastern Connecticut State University', 'Guilford College', 'Southern Illinois University-Edwardsville',
    'Bay Path University', 'Montclair State University', 'Dominican University New York',
    'University of South Carolina Aiken', 'Southwest Baptist University', 'Farmingdale State College',
    'Union Adventist University', 'Bethel College-North Newton', 'Dillard University',
    'Youngstown State University', 'University of Houston-Clear Lake', 'University of North Georgia',
    'Wingate University', 'DeVry College of New York', 'DeVry University-Arizona',
    'DeVry University-California', 'DeVry University-Florida', 'DeVry University-Georgia',
    'DeVry University-Nevada', 'DeVry University-New Jersey', 'DeVry University-North Carolina',
    'DeVry University-Ohio', 'DeVry University-Texas', 'DeVry University-Virginia',
    'Louisiana Christian University', 'Black Hills State University', 'DeVry University-Illinois',
    'Huntingdon College', 'University of Science and Arts of Oklahoma', 'Tennessee Wesleyan University',
    'University of the Ozarks', 'Aurora University', 'Millikin University', 'Midland University',
    'Ursuline College', 'Northern State University', 'Georgia State University',
    'Southern Arkansas University Main Campus', 'Nicholls State University', 'Appalachian Bible College',
    'Trinity Christian College', 'Western Kentucky University', 'University of New Orleans',
    'SUNY College of Technology at Alfred', 'Georgia State University-Perimeter College',
    'University of Arkansas at Little Rock', 'McNeese State University', 'Blue Mountain Christian University',
    'Austin Peay State University', 'Northwestern State University of Louisiana',
    'Missouri Southern State University', 'Northwest Missouri State University', 'Southern Virginia University',
    'University of Wisconsin-Milwaukee Flex', 'University of Wisconsin-Parkside Flex',
    'Faith Baptist Bible College and Theological Seminary', 'University of Central Oklahoma',
    'Shippensburg University of Pennsylvania', 'John A Gupton College', 'Arkansas Tech University',
    'University of Bridgeport', 'Morehouse College', 'Anderson University', 'Emmaus Bible College',
    'Mount Mercy University', 'Emporia State University', 'Manhattan Christian College',
    'Pittsburg State University', 'Southeastern Louisiana University', 'University of Detroit Mercy',
    'Bemidji State University', 'Minnesota State University-Mankato', 'Minnesota State University Moorhead',
    'Avila University', 'University of Central Missouri', 'Logan University', 'University of New Mexico-Main Campus',
    'Southern Wesleyan University', 'University of Memphis', 'Texas A & M University-Corpus Christi',
    'Texas State University', 'Saint Martin\'s University', 'University of Wisconsin-Whitewater',
    'University of Wisconsin-Green Bay', 'University of Wisconsin-Parkside', 'University of Wisconsin-Milwaukee',
    'University of Wisconsin-River Falls', 'Tuskegee University', 'The University of Tennessee Southern',
    'Louisiana State University-Shreveport', 'Malone University', 'Indiana University-East',
    'Thomas More University', 'Grand Valley State University', 'University of Nevada-Las Vegas',
    'Capital University', 'Georgetown College', 'Saint Cloud State University', 'Kent State University at Kent',
    'Hardin-Simmons University', 'Spring Hill College', 'La Roche University', 'Franklin Pierce University',
    'Dallas Baptist University', 'Franklin College', 'Lake Superior State University',
    'University of Mount Saint Vincent', 'Southern California Institute of Architecture', 'Huntington University',
    'Aquinas College', 'University of Mary Hardin-Baylor', 'Husson University', 'Purdue University Fort Wayne',
    'Trevecca Nazarene University', 'Saint Leo University', 'Castleton University',
    'Grace College and Theological Seminary', 'Xavier University of Louisiana', 'University of North Florida',
    'Central Michigan University', 'Augusta University', 'Indiana University-Kokomo',
    'Framingham State University', 'Western Michigan University', 'Coastal Carolina University',
    'University of Northern Colorado', 'Winthrop University', 'Brigham Young University-Idaho',
    'Elmhurst University', 'University of Mount Union', 'Piedmont University', 'Carroll College',
    'Randolph College', 'University of Southern Maine', 'Murray State University',
    'University of Akron Main Campus', 'University of Maine at Farmington', 'Bridgewater State University',
    'Salem State University', 'Culinary Institute of America', 'St. Thomas Aquinas College', 'SUNY Old Westbury',
    'Gwynedd Mercy University', 'Thaddeus Stevens College of Technology', 'University of Akron Wayne College',
    'West Virginia University', 'Illinois State University', 'Southeastern Baptist Theological Seminary',
    'The University of Texas at San Antonio', 'West Virginia University Institute of Technology',
    'Florida Atlantic University', 'The Southern Baptist Theological Seminary', 'Friends University',
    'Hartwick College', 'Oral Roberts University', 'Carson-Newman University', 'The University of Texas at Arlington',
    'University of Hawaii at Manoa', 'Wartburg College', 'Midway University', 'Marywood University',
    'Florida College', 'Florida Gulf Coast University', 'Toccoa Falls College', 'Gardner-Webb University',
    'East Tennessee State University', 'The University of Texas at Tyler', 'Buena Vista University',
    'Georgian Court University', 'University of La Verne', 'Concordia University-Nebraska',
    'Bowling Green State University-Main Campus', 'Texas Lutheran University', 'Longwood University',
    'Maranatha Baptist University', 'Central College', 'Delaware Valley University', 'University of South Alabama',
    'University of Central Arkansas', 'Wichita State University', 'Bryn Athyn College of the New Church',
    'Arkansas State University', 'University of Nebraska at Kearney', 'Mount Vernon Nazarene University',
    'Kentucky Mountain Bible College', 'University of Nebraska at Omaha', 'Baptist Health Sciences University',
    'Middle Tennessee State University', 'Visible Music College', 'North Park University',
    'Indiana Wesleyan University-Marion', 'Franciscan Missionaries of Our Lady University',
    'Culver-Stockton College', 'North Dakota State University-Main Campus', 'Cabrini University',
    'Waynesburg University', 'Southern Adventist University', 'University of Wisconsin-Stout',
    'University of Wisconsin-Stevens Point', 'Pennsylvania College of Health Sciences',
    'Neumont College of Computer Science', 'University of Northern Iowa', 'Winona State University',
    'Lancaster Bible College', 'South Dakota State University', 'The University of Tennessee-Martin',
    'Iona University', 'York College of Pennsylvania', 'University of South Dakota', 'Randolph-Macon College',
    'Northern Kentucky University', 'College of the Ozarks', 'Indiana University-Southeast',
    'Fitchburg State University', 'Stephens College', 'Mercy University', 'Catawba College',
    'Fairleigh Dickinson University-Florham Campus', 'Principia College', 'University of Illinois Springfield',
    'University of Lynchburg', 'Fairleigh Dickinson University-Metropolitan Campus',
    'Brigham Young University-Hawaii', 'Western Connecticut State University', 'Lynn University',
    'Palm Beach Atlantic University', 'St Catherine University', 'Western Carolina University',
    'University of North Texas', 'Bridgewater College', 'University of Idaho', 'Lake Erie College',
    'Northland College', 'William Jessup University', 'Mount Saint Mary College', 'Texas A & M University-Kingsville',
    'Montana Technological University', 'The Evergreen State College', 'University of Louisiana at Monroe',
    'Azusa Pacific University', 'Goshen College', 'D\'Youville  University', 'Kennesaw State University',
    'Lewis University', 'William Peace University', 'American College of the Building Arts',
    'Worcester State University', 'Concordia University-Wisconsin', 'Caldwell University',
    'Concordia University Ann Arbor', 'North Central College', 'Towson University', 'McMurry University',
    'Northwest Nazarene University', 'University of Southern Indiana', 'College of Our Lady of the Elms',
    'Oakland University', 'Kutztown University of Pennsylvania', 'La Salle University', 'Monmouth College',
    'Dakota State University', 'Saint Francis University', 'Niagara University', 'Converse University',
    'Maryville College', 'Georgia College & State University', 'Saint Johns University', 'Augustana College',
    'Oklahoma State University-Main Campus', 'Washington & Jefferson College', 'Mount St. Mary\'s University',
    'University of Missouri-St Louis', 'William Jewell College', 'Otterbein University', 'Fort Lewis College',
    'Wayne State University', 'Bethany Lutheran College', 'Missouri Baptist University',
    'Missouri State University-Springfield', 'Oklahoma Christian University', 'Freed-Hardeman University',
    'The University of Tennessee-Chattanooga', 'Houston Christian University', 'Regis University',
    'Lasell University', 'University of Massachusetts-Dartmouth', 'Moravian University',
    'University of Southern Mississippi', 'University of Colorado Denver/Anschutz Medical Campus',
    'Metropolitan State University', 'Saint Mary\'s University of Minnesota', 'Stockton University',
    'William Paterson University of New Jersey', 'Oklahoma City University', 'Pacific University',
    'Lycoming College', 'Millersville University of Pennsylvania', 'Point Park University',
    'Christian Brothers University', 'Regent University', 'University of Wisconsin-Platteville',
    'Ashland University', 'Hamline University', 'Saint Vincent College', 'Saint Ambrose University',
    'University of Louisville', 'Webster University', 'Florida International University',
    'Western Colorado University', 'The College of Saint Rose', 'Multnomah University',
    'University of Michigan-Dearborn', 'SUNY Brockport', 'Presbyterian College', 'Indiana University-Indianapolis',
    'Montana State University', 'Wilkes University', 'SUNY College at Plattsburgh', 'Seton Hill University',
    'Carthage College', 'University of Health Sciences and Pharmacy in St. Louis', 'Baldwin Wallace University',
    'University of North Carolina at Charlotte', 'King\'s College', 'Howard University',
    'Nova Southeastern University', 'Jacksonville University', 'St Bonaventure University',
    'West Chester University of Pennsylvania', 'Saint Edward\'s University', 'University of West Florida',
    'University of St Francis', 'Maine Maritime Academy', 'SUNY at Fredonia', 'University of Arkansas',
    'Siena College', 'Flagler College', 'Maryland Institute College of Art', 'University of Saint Joseph',
    'Virginia Commonwealth University', 'University of St Thomas', 'Abilene Christian University-Undergraduate Online',
    'Old Dominion University', 'Abilene Christian University', 'Roanoke College', 'Hawaii Pacific University',
    'State University of New York at Oswego', 'Lee University', 'The College of Idaho', 'Chatham University',
    'Lindenwood University', 'St. Joseph\'s University-New York', 'Oregon Institute of Technology',
    'University of Rhode Island', 'Citadel Military College of South Carolina', 'Saint Norbert College',
    'Savannah College of Art and Design', 'Ouachita Baptist University', 'University of Colorado Colorado Springs',
    'University of New Haven', 'University of Evansville', 'Immaculata University', 'Moore College of Art and Design',
    'Wisconsin Lutheran College', 'Harding University', 'Dordt University', 'Hampden-Sydney College',
    'Methodist University', 'Mount St. Joseph University', 'Andrews University', 'St. John Fisher University',
    'SUNY Oneonta', 'University of Northwestern-St Paul', 'College of Saint Benedict', 'Walsh University',
    'Appalachian State University', 'Utah State University', 'William Carey University',
    'Centenary College of Louisiana', 'Ohio University-Main Campus', 'Viterbo University', 'University of Kentucky',
    'Louisiana Tech University', 'Bethel University', 'Concordia University-Saint Paul', 'Mississippi College',
    'University of North Carolina at Greensboro', 'Cleveland Institute of Art', 'Tennessee Technological University',
    'University of Wisconsin-Eau Claire', 'University of Wisconsin-La Crosse', 'Milligan University',
    'Ball State University', 'Bellarmine University', 'Elizabethtown College', 'Augustana University',
    'Dominican University of California', 'University of Kansas', 'University of Nebraska-Lincoln',
    'Utica University', 'University at Albany', 'Queens University of Charlotte', 'Western New England University',
    'Martin Luther College', 'University of Mary', 'George Fox University', 'Susquehanna University',
    'Iowa State University', 'Rowan University', 'University of Massachusetts-Boston', 'Texas Tech University',
    'Northwest University', 'Colorado State University-Fort Collins', 'University of Mississippi',
    'University of Toledo', 'Christopher Newport University', 'Canisius University', 'Houghton University',
    'Fisk University', 'University of Hartford', 'Nebraska Wesleyan University', 'Lebanon Valley College',
    'Virginia Military Institute', 'University of Maine', 'Molloy College', 'Wagner College', 'Monmouth University',
    'Suffolk University', 'DeSales University', 'Stetson University', 'Endicott College',
    'Marymount Manhattan College', 'Seattle Pacific University', 'Florida Southern College',
    'Oglethorpe University', 'Whitworth University', 'Bradley University', 'Berry College',
    'University of North Carolina Asheville', 'Alfred University', 'SUNY Maritime College',
    'Arcadia University', 'Widener University', 'Carroll University', 'Florida Institute of Technology-Online',
    'Florida Institute of Technology', 'Hope College', 'Hanover College', 'Ramapo College of New Jersey',
    'Rider University', 'Franciscan University of Steubenville', 'University of New Hampshire-Main Campus',
    'University of Redlands', 'Gordon College', 'Wentworth Institute of Technology', 'Mississippi State University',
    'Roger Williams University', 'University of New Hampshire at Manchester', 'Quinnipiac University',
    'Springfield College', 'Wittenberg University', 'Salve Regina University', 'United States Merchant Marine Academy',
    'Birmingham-Southern College', 'John Brown University', 'Saint Anselm College', 'St. John\'s University-New York',
    'Long Island University', 'University of Mobile', 'Benedictine College', 'Berea College',
    'Concordia College at Moorhead', 'University of Minnesota-Duluth', 'The College of Saint Scholastica',
    'Rockhurst University', 'Elmira College', 'Pace University', 'High Point University', 'Meredith College',
    'Ohio Dominican University', 'DePaul University', 'Louisiana State University and Agricultural & Mechanical College',
    'Drury University', 'University of Iowa', 'Millsaps College', 'Le Moyne College', 'Samford University',
    'Hollins University', 'University of Arizona', 'Messiah University', 'Wabash College', 'Whittier College',
    'University of Missouri-Kansas City', 'University of Illinois Chicago', 'MCPHS University',
    'Sweet Briar College', 'Taylor University', 'Emmanuel College', 'Adelphi University',
    'Minneapolis College of Art and Design', 'University of South Florida', 'New College of Florida',
    'University of Utah', 'Salisbury University', 'University of Scranton', 'Eckerd College',
    'Xavier University', 'Ohio Wesleyan University', 'University of Tulsa', 'College of Charleston',
    'LeTourneau University', 'Nazareth University', 'University of Oklahoma-Norman Campus',
    'Luther College', 'University of Houston', 'James Madison University', 'Saint Joseph\'s University',
    'Austin College', 'Juniata College', 'Thomas Jefferson University', 'Michigan Technological University',
    'Drew University', 'Manhattan College', 'Embry-Riddle Aeronautical University-Prescott',
    'Embry-Riddle Aeronautical University-Worldwide', 'Hendrix College', 'Truman State University',
    'Embry-Riddle Aeronautical University-Daytona Beach', 'Westminster University',
    'University of Missouri-Columbia', 'Biola University', 'Transylvania University', 'Hastings College',
    'Cedarville University', 'University of Cincinnati-Main Campus', 'South Dakota School of Mines and Technology',
    'Cornell College', 'Saint Michael\'s College', 'State University of New York at New Paltz',
    'University of Massachusetts-Lowell', 'George Mason University', 'University of North Carolina School of the Arts',
    'Bryant University', 'Duquesne University', 'Western Washington University', 'California Lutheran University',
    'Goucher College', 'University of Alabama in Huntsville', 'Saint Mary\'s College', 'Washington College',
    'Champlain College', 'Valparaiso University', 'University of Mary Washington', 'Earlham College',
    'St. Mary\'s College of Maryland', 'Butler University', 'Southwestern University', 'Illinois Wesleyan University',
    'Calvin University', 'New York Institute of Technology', 'Pennsylvania State University-Penn State Shenango',
    'Pennsylvania State University-Main Campus', 'Kalamazoo College', 'John Carroll University',
    'Pennsylvania State University-Penn State Harrisburg', 'Pennsylvania State University-Penn State Erie-Behrend College',
    'Pennsylvania State University-Penn State York', 'Pennsylvania State University-Penn State Berks',
    'Pennsylvania State University-Penn State Wilkes-Barre', 'Pennsylvania State University-Penn State Abington',
    'Pennsylvania State University-Penn State Brandywine', 'Pennsylvania State University-Penn State Lehigh Valley',
    'Pennsylvania State University-Penn State Beaver', 'Pennsylvania State University-Penn State Altoona',
    'Pennsylvania State University-World Campus', 'Pennsylvania State University-Penn State New Kensington',
    'Pennsylvania State University-Penn State Hazleton', 'Pennsylvania State University-Penn State Scranton',
    'Pennsylvania State University-Penn State DuBois', 'Pennsylvania State University-Penn State Greater Allegheny',
    'Pennsylvania State University-Penn State Mont Alto', 'Pennsylvania State University-Penn State Fayette- Eberly',
    'Pennsylvania State University-Penn State Schuylkill', 'Rollins College', 'Kettering University',
    'University of North Carolina Wilmington', 'Allegheny College', 'Belmont University', 'Seattle University',
    'University of Oregon', 'SUNY College at Geneseo', 'Michigan State University', 'DePauw University',
    'Lipscomb University', 'University of the Pacific', 'Agnes Scott College', 'Grove City College',
    'University of Dallas', 'Elon University', 'Virginia Wesleyan University', 'University of Central Florida',
    'Texas A & M University-College Station', 'Lake Forest College', 'SUNY at Purchase College',
    'Union University', 'Clarkson University', 'Ohio Northern University', 'New Saint Andrews College',
    'The College of New Jersey', 'University of Dayton', 'Loyola University Maryland', 'Hofstra University',
    'University of Connecticut', 'University of Connecticut-Avery Point', 'University of Connecticut-Hartford Campus',
    'University of Connecticut-Stamford', 'University of Connecticut-Waterbury Campus', 'Mercer University',
    'Marist College', 'University at Buffalo', 'University of Delaware', 'University of St Thomas',
    'University of Alabama at Birmingham', 'Florida Polytechnic University', 'Auburn University',
    'Ursinus College', 'United States Coast Guard Academy', 'Roberts Wesleyan University',
    'University of Maryland-Baltimore County', 'Simmons University', 'School of Visual Arts',
    'The University of Tennessee-Knoxville', 'Wofford College', 'University of Colorado Boulder',
    'University of Puget Sound', 'DigiPen Institute of Technology', 'Marquette University',
    'The King\'s College', 'The University of Alabama', 'Drake University', 'University of South Carolina-Columbia',
    'The University of Texas at Dallas', 'Beloit College', 'Texas Christian University', 'Loyola University Chicago',
    'Ithaca College', 'Florida State University', 'Knox College', 'Miami University-Oxford', 'Covenant College',
    'Chapman University', 'Seton Hall University', 'Pratt Institute-Main', 'Holy Cross College',
    'Gustavus Adolphus College', 'Missouri University of Science and Technology',
    'Albany College of Pharmacy and Health Sciences', 'Warren Wilson College', 'University of Washington-Seattle Campus',
    'University of Washington-Tacoma Campus', 'Indiana University-Bloomington', 'University of Washington-Bothell Campus',
    'University of San Francisco', 'Fairfield University', 'New Jersey Institute of Technology',
    'United States Naval Academy', 'University of Portland', 'Thomas Aquinas College', 'Illinois Institute of Technology',
    'Gonzaga University', 'Muhlenberg College', 'St Lawrence University', 'Drexel University', 'Providence College',
    'University of Georgia', 'Bennington College', 'Virginia Polytechnic Institute and State University',
    'University of Pittsburgh-Titusville', 'University of Pittsburgh-Pittsburgh Campus',
    'Pacific Lutheran University', 'University of Pittsburgh-Greensburg', 'University of Pittsburgh-Johnstown',
    'University of Pittsburgh-Bradford', 'Hobart William Smith Colleges', 'Saint Louis University',
    'Clemson University', 'Touro University', 'Creighton University', 'Bentley University',
    'Wheaton College (Massachusetts)', 'Baylor University', 'University of Denver', 'Soka University of America',
    'University of Minnesota-Twin Cities', 'University of Minnesota-Rochester', 'Purdue University-Main Campus',
    'United States Military Academy', 'Patrick Henry College', 'The University of the South', 'Sarah Lawrence College',
    'University of Vermont', 'Lawrence University', 'Syracuse University', 'College of the Holy Cross',
    'Furman University', 'The College of Wooster', 'Rutgers University-Newark', 'Rutgers University-New Brunswick',
    'Centre College', 'Lewis & Clark College', 'Rutgers University-Camden', 'Wheaton College',
    'Rochester Institute of Technology', 'North Carolina State University at Raleigh', 'Gettysburg College',
    'Clark University', 'Emerson College', 'The University of Texas at Austin', 'University of Wisconsin-Madison',
    'University of Massachusetts-Amherst', 'Brigham Young University', 'St Olaf College',
    'Loyola Marymount University', 'St. John\'s College', 'Santa Clara University', 'Westmont College',
    'St. John\'s College', 'Rhodes College', 'American University', 'Ohio State University-Main Campus',
    'Franklin and Marshall College', 'Trinity College', 'University of Florida', 'Denison University',
    'University of Florida-Online', 'Trinity University', 'Skidmore College', 'Union College',
    'Rose-Hulman Institute of Technology', 'Pepperdine University', 'United States Air Force Academy',
    'Colorado College', 'Colorado School of Mines', 'Bryn Mawr College', 'Yeshiva University',
    'Bucknell University', 'University of Miami', 'Simpson College', 'Stony Brook University', 'Lafayette College',
    'Fordham University', 'Whitman College', 'Lehigh University', 'George Washington University', 'Reed College',
    'Wesleyan University', 'Binghamton University', 'Connecticut College', 'Macalester College',
    'Mount Holyoke College', 'Rhode Island School of Design', 'Occidental College', 'Babson College',
    'Davidson College', 'University of Illinois Urbana-Champaign', 'Hillsdale College',
    'Tulane University of Louisiana', 'Southern Methodist University', 'Oberlin College',
    'University of North Carolina at Chapel Hill', 'Kenyon College', 'Webb Institute', 'Boston University',
    'Villanova University', 'Smith College', 'Stevens Institute of Technology', 'Rensselaer Polytechnic Institute',
    'University of Maryland-College Park', 'William & Mary', 'Scripps College',
    'The Cooper Union for the Advancement of Science and Art', 'Brandeis University',
    'University of Michigan-Ann Arbor', 'University of Rochester', 'University of Richmond',
    'Georgia Institute of Technology-Main Campus', 'Grinnell College', 'Bates College', 'Colgate University',
    'Carleton College', 'Vassar College', 'Case Western Reserve University', 'University of Virginia-Main Campus',
    'Emory University', 'Emory University-Oxford College', 'Barnard College', 'Washington and Lee University',
    'Boston College', 'Wellesley College', 'Hamilton College', 'Colby College', 'Middlebury College',
    'Northeastern University', 'Haverford College', 'Georgetown University', 'Swarthmore College',
    'Jewish Theological Seminary of America', 'Amherst College', 'Tufts University', 'Claremont McKenna College',
    'University of Notre Dame', 'Pomona College', 'University of Southern California', 'Bowdoin College',
    'Washington University in St Louis', 'Northwestern University', 'Cornell University', 'New York University',
    'University of Chicago', 'Franklin W Olin College of Engineering', 'Harvey Mudd College', 'Dartmouth College',
    'Williams College', 'Columbia University in the City of New York', 'Princeton University',
    'Carnegie Mellon University', 'University of Pennsylvania', 'Vanderbilt University', 'Rice University',
    'Yale University', 'Brown University', 'Johns Hopkins University', 'Harvard University', 'Stanford University',
    'Duke University', 'Massachusetts Institute of Technology'
]

column_list = [
    'INSTNM', 'ADMCON7', 'PCTPELL', 'UGDS', 'UGDS_BLACK', 'UGDS_HISP',
    'ADM_RATE', 'ADM_RATE_ALL', 'SAT_AVG', 'SAT_AVG_ALL', 'RET_FT4',
    'WDRAW_ORIG_YR2_RT', 'LO_INC_WDRAW_ORIG_YR2_RT',
    'MD_INC_WDRAW_ORIG_YR2_RT', 'HI_INC_WDRAW_ORIG_YR2_RT',
    'PELL_WDRAW_ORIG_YR2_RT', 'NOPELL_WDRAW_ORIG_YR2_RT',
    'WDRAW_ORIG_YR4_RT', 'LO_INC_WDRAW_ORIG_YR4_RT',
    'MD_INC_WDRAW_ORIG_YR4_RT', 'HI_INC_WDRAW_ORIG_YR4_RT',
    'PELL_WDRAW_ORIG_YR4_RT', 'NOPELL_WDRAW_ORIG_YR4_RT',
    'C100_4', 'C150_4', 'C150_4_PELL',
    'C150_4_NOLOANNOPELL', 'C150_4_LOANNOPELL',
    'COSTT4_A', 'PCTFLOAN', 'DEBT_MDN', 'LOCALE', 'FEMALE',
    'UGDS_WHITE', 'UGDS_ASIAN', 'UGDS_AIAN', 'UGDS_NHPI', 'UGDS_2MOR',
    'UNITID', # Include UNITID to identify institutions uniquely across years
    'OPEID', # Include OPEID for identification
    'ICLEVEL', 'CONTROL', # Add some key institutional controls
    'YEAR'
]

csv_files = sorted(glob.glob(os.path.join(data_directory, '*.csv')), reverse=True)

all_data = []

if not csv_files:
    print(f"No CSV files found in the directory: {data_directory}")
    print("Please check the 'data_directory' variable in the script.")
else:
    print(f"Found {len(csv_files)} CSV files to process.")
    for file_path in csv_files:
        print(f"Processing file: {file_path}")
        try:
            df = pd.read_csv(file_path, low_memory=False)

            # Extract the year from the filename (format like 'MERGEDYYYY_YY_PP.csv')
            filename = os.path.basename(file_path)
            year_match = filename.split('_')[0].replace('MERGED', '')
            df['YEAR'] = year_match if year_match.isdigit() else filename

            filtered_df = df[df['INSTNM'].isin(college_list)].copy()

            present_columns = [col for col in column_list if col in filtered_df.columns]
            
            missing_columns = [col for col in column_list if col not in filtered_df.columns]
            if missing_columns:
                print(f"  Missing columns in this file: {missing_columns}")
            else:
                print("  All requested columns are present in this file.")
            
            selected_df = filtered_df[present_columns]

            all_data.append(selected_df)

            print(f"  Extracted {len(present_columns)} cols for specified colleges.")
            print(f"  Extracted {len(selected_df)} rows for specified colleges.\n")

        except FileNotFoundError:
            print(f"  Error: File not found at {file_path}")
        except pd.errors.EmptyDataError:
            print(f"  Warning: File {file_path} is empty. Skipping.")
        except Exception as e:
            print(f"  An error occurred while processing {file_path}: {e}")

    if all_data:
        combined_df = pd.concat(all_data, ignore_index=True)
        combined_df.to_csv(output_filename, index=False)

        print(f"\nSuccessfully extracted data for {len(combined_df)} rows across all files.")
        print(f"Filtered data saved to: {output_filename}")
    else:
        print("\nNo data was extracted. Check the data directory and college names.")
